namespace Sandbox
{
    using System;
    using System.Diagnostics;
    using System.IO;
    using NUnit.Framework;
    using VanceStubbs;
    using VanceStubbs.Tests.Types;

    public class Program
    {
        public static void Main()
        {
            var peverifyPath = @"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\PEVerify.exe";
            if (!File.Exists(peverifyPath))
            {
                Console.WriteLine("PEVerify.exe not found at the given path, verification skipped");
                peverifyPath = null;
            }

            try
            {
                var proxy = VanceStubbs.Stubs
                    .NotifyPropertyChangedProxy<AbstractProperty>();

                proxy.GetSet = 4;
                proxy.PropertyChanged += (sender, args) =>
                {
                    if (args.PropertyName == nameof(proxy.GetSet))
                    {
                        Assert.Pass();
                    }
                };
                proxy.GetSet = 16;
                Assert.Fail();
            }
            catch (Exception)
            {
                DynamicAssembly.Default.Save();
                if (peverifyPath != null)
                {
                    var process = Process.Start(new ProcessStartInfo(peverifyPath)
                    {
                        Arguments = "stubsautogenerated.dll",
                        CreateNoWindow = false,
                        UseShellExecute = false
                    });
                }

                throw;
            }
        }
    }
}
